import type { PackageRecommendationSource } from "./types";

/**
 * Deterministic mock package catalog defined in docs/RECOMMENDATION_CONTRACT.md section 13.
 * Fictional prototype data for competition evaluation.
 */
export const MOCK_RECOMMENDATION_PACKAGES: PackageRecommendationSource[] = [
  {
    id: "slow_green_day",
    title: "Sehari Pelan di Lereng Hijau",
    shortSummary: "Aktivitas santai menikmati panorama perkebunan teh dan lereng asri Batu.",
    destinationName: "Lereng Hijau Batu",
    locationLabel: "Batu / Malang Raya",
    visualAsset: "/assets/packages/slow_green_day.jpg",
    status: "LIVE",
    verificationLevel: "BASIC",
    pricePerPerson: 275000,
    durationType: "FULL_DAY",
    departureAreas: ["MALANG"],
    experienceIntents: ["RECHARGE", "NATURE", "REFLECTION"],
    activityTags: ["NATURE_SCENERY", "MINDFULNESS_RELAXATION", "LIGHT_EXPLORATION"],
    suitableGroupTypes: ["SOLO", "PARTNER", "FRIENDS"],
    suitableGroupSizeBands: ["ONE", "TWO", "THREE_TO_FOUR"],
    rating: 4.85,
    popularityRank: 95,
  },
  {
    id: "creative_village_halfday",
    title: "Ruang Kreatif Desa",
    shortSummary: "Belajar kerajinan tangan lokal dan mengenal kehidupan desa yang tenang.",
    destinationName: "Desa Wisata Budaya",
    locationLabel: "Malang Raya",
    visualAsset: "/assets/packages/creative_village.jpg",
    status: "LIVE",
    verificationLevel: "BASIC",
    pricePerPerson: 190000,
    durationType: "HALF_DAY",
    departureAreas: ["MALANG"],
    experienceIntents: ["NOVELTY", "REFLECTION", "SOCIAL"],
    activityTags: ["LOCAL_CULTURE", "CREATIVE_WORKSHOP"],
    suitableGroupTypes: ["PARTNER", "FRIENDS", "FAMILY"],
    suitableGroupSizeBands: ["TWO", "THREE_TO_FOUR", "FIVE_PLUS"],
    rating: 4.75,
    popularityRank: 88,
  },
  {
    id: "mindful_morning",
    title: "Pagi Hening & Mindful Reset",
    shortSummary: "Sesi relaksasi pagi hari di tengah keheningan alam pegunungan sejuk.",
    destinationName: "Oase Hening Trawas",
    locationLabel: "Mojokerto Raya",
    visualAsset: "/assets/packages/mindful_morning.jpg",
    status: "LIVE",
    verificationLevel: "BASIC",
    pricePerPerson: 225000,
    durationType: "HALF_DAY",
    departureAreas: ["SURABAYA"],
    experienceIntents: ["RECHARGE", "REFLECTION", "NATURE"],
    activityTags: ["MINDFULNESS_RELAXATION", "NATURE_SCENERY"],
    suitableGroupTypes: ["SOLO", "PARTNER", "FRIENDS"],
    suitableGroupSizeBands: ["ONE", "TWO", "THREE_TO_FOUR"],
    rating: 4.9,
    popularityRank: 92,
  },
  {
    id: "light_mountain_explore",
    title: "Jelajah Santai Pegunungan",
    shortSummary: "Jalan santai outdoor menyusuri jalur pegunungan yang menyegarkan tubuh.",
    destinationName: "Taman Alam Prigen",
    locationLabel: "Pasuruan Raya",
    visualAsset: "/assets/packages/mountain_explore.jpg",
    status: "LIVE",
    verificationLevel: "BASIC",
    pricePerPerson: 325000,
    durationType: "FULL_DAY",
    departureAreas: ["SURABAYA"],
    experienceIntents: ["NOVELTY", "ACTIVE", "NATURE"],
    activityTags: ["LIGHT_EXPLORATION", "OUTDOOR_ACTIVE", "NATURE_SCENERY"],
    suitableGroupTypes: ["PARTNER", "FRIENDS", "FAMILY"],
    suitableGroupSizeBands: ["TWO", "THREE_TO_FOUR", "FIVE_PLUS"],
    rating: 4.8,
    popularityRank: 86,
  },
  {
    id: "weekend_nature_reset",
    title: "Weekend Nature Reset",
    shortSummary: "Recharge akhir pekan dengan bermalam di alam terbuka yang tenang.",
    destinationName: "Lembah Alam Pacet",
    locationLabel: "Mojokerto Raya",
    visualAsset: "/assets/packages/weekend_reset.jpg",
    status: "LIVE",
    verificationLevel: "BASIC",
    pricePerPerson: 475000,
    durationType: "TWO_D_ONE_N",
    departureAreas: ["SURABAYA"],
    experienceIntents: ["RECHARGE", "NATURE", "SOCIAL"],
    activityTags: ["NATURE_SCENERY", "MINDFULNESS_RELAXATION", "LIGHT_EXPLORATION"],
    suitableGroupTypes: ["PARTNER", "FRIENDS", "FAMILY"],
    suitableGroupSizeBands: ["TWO", "THREE_TO_FOUR", "FIVE_PLUS"],
    rating: 4.88,
    popularityRank: 90,
  },
];
